Repository bcgov/CIT, pull requests merged in 2021-03, with the labels that each got.

#496 CIT 25 import data fixes and additions
  .DS_Store
  .gitignore
  cit-api/.DS_Store
  cit-api/pipeline/importers/communities.py
  cit-api/pipeline/importers/databc_resource.py
  cit-api/pipeline/importers/shp_resource.py
  cit-api/pipeline/importers/utils.py
  cit-api/pipeline/management/commands/bootstrap.py
  cit-api/pipeline/migrations/0121_auto_20210301_0400.py
  cit-api/pipeline/models/__init__.py
  cit-api/pipeline/models/bc_floodplain.py
  cit-api/pipeline/models/census.py
  cit-api/pipeline/models/census_economic_region.py
  cit-api/pipeline/models/community.py
  cit-api/pipeline/models/general.py
  cit-api/pipeline/models/health_authority_boundary.py
  cit-api/pipeline/models/lake.py
  cit-api/pipeline/models/location_assets.py
  cit-api/pipeline/models/natural_resource_region.py
  cit-api/pipeline/models/opportunity.py
  cit-api/pipeline/models/permitted_major_mines.py
  cit-api/pipeline/models/provincial_electoral_district.py
  cit-api/pipeline/models/railway.py
  cit-api/pipeline/models/river.py
  cit-api/pipeline/pipeline-urls.py
  cit-api/requirements.txt
Labels: enhancement

#498 CIT 154 import items without names and CIT 161 Limit the lakes import.
  cit-api/pipeline/importers/databc_resource.py
  cit-api/pipeline/importers/utils.py
  cit-api/pipeline/management/commands/bootstrap.py
  cit-api/pipeline/migrations/0122_auto_20210301_0649.py
  cit-api/pipeline/models/river.py
Labels: bug, enhancement

#507 CIT-64: Added approval workflow for single opportunity
  cit3.0-web/src/components/Headers/Header/Header.scss
  cit3.0-web/src/components/Headers/Header/UserProfile.js
  cit3.0-web/src/components/LocationsPanel/LocationsPanel.css
  cit3.0-web/src/components/LocationsPanel/LocationsPanel.js
  cit3.0-web/src/components/LocationsPanel/LocationsPanel.module.css
  cit3.0-web/src/components/Map/Map.js
  cit3.0-web/src/components/Map/map.css
  cit3.0-web/src/components/OpportunityApprovalItem/OpportunityApprovalItem.js
  cit3.0-web/src/components/OpportunityApproveCallout/OpportunityApproveCallout.css
  cit3.0-web/src/components/OpportunityApproveCallout/OpportunityApproveCallout.js
  cit3.0-web/src/components/OpportunityApproveCallout/OpportunityApproveCallout.stories.js
  cit3.0-web/src/components/OpportunityApproveCallout/OpportunityApproveCallout.test.js
  cit3.0-web/src/components/OpportunityListItem/OpportunityListItem.js
  cit3.0-web/src/components/OpportunityView/OpportunityView.css
  cit3.0-web/src/components/OpportunityView/OpportunityView.js
  cit3.0-web/src/components/Page/OpportunityApproveListPage/ApprovalFlyoutContent.js
  cit3.0-web/src/components/Page/OpportunityApprovePage/OpportunityApprovePage.js
  cit3.0-web/src/components/Page/OpportunityPage/OpportunityPage.js
  cit3.0-web/src/components/Page/ReviewOpportunity/ReviewOpportunity.js
  cit3.0-web/src/components/Page/ReviewSubmitted/ReviewSubmitted.js
  cit3.0-web/src/store/actions/opportunity.js
  cit3.0-web/src/store/actions/options.js
  cit3.0-web/src/store/constants/action-types.js
  cit3.0-web/src/store/constants/api-urls.js
  cit3.0-web/src/store/factory/OpportunityFactory.js
  cit3.0-web/src/store/models/opportunity.js
  cit3.0-web/src/store/reducer.js
  cit3.0-web/src/store/reducers/opportunity.js
  cit3.0-web/src/store/reducers/options.js
Labels: enhancement

#515 CIT-127: Added service queries
  cit-api/pipeline/migrations/0127_auto_20210315_2241.py
  cit-api/pipeline/models/opportunity.py
  cit-api/pipeline/opportunity-urls.py
  cit-api/pipeline/serializers/opportunity.py
  cit-api/pipeline/views/opportunity.py
  cit-api/pipeline/views/proximity.py
  cit3.0-web/src/components/AddMarker/ResourceMarker.js
  cit3.0-web/src/components/MapContainer/MapContainer.js
  cit3.0-web/src/components/OpportunityView/Resource.js
  cit3.0-web/src/helpers/resourceCalls.js
  cit3.0-web/src/store/factory/OpportunityFactory.js
  cit3.0-web/src/store/models/opportunity.js
  cit3.0-web/src/store/reducers/opportunity.js
Labels: WIP

#517 CIT 135 Import BCA data
  .DS_Store
  cit-api/.DS_Store
  cit-api/pipeline/importers/csv_resource.py
  cit-api/pipeline/importers/utils.py
  cit-api/pipeline/management/commands/bootstrap.py
  cit-api/pipeline/migrations/0128_bcassessmentcensussubdivision_bcassessmenteconomicregion_bcassessmentregionaldistrict.py
  cit-api/pipeline/models/__init__.py
  cit-api/pipeline/models/bc_assessment/bc_assessment_census_subdivision.py
  cit-api/pipeline/models/bc_assessment/bc_assessment_economic_region.py
  cit-api/pipeline/models/bc_assessment/bc_assessment_regional_district.py
Labels: enhancement

#529 Fixed bug on SRID of geometry columns as well as reverted them all to 4326.
  .DS_Store
  cit-api/.DS_Store
  cit-api/pipeline/importers/communities.py
  cit-api/pipeline/importers/databc_resource.py
  cit-api/pipeline/importers/shp_resource.py
  cit-api/pipeline/importers/utils.py
  cit-api/pipeline/migrations/0129_auto_20210318_0256.py
  cit-api/pipeline/models/bc_floodplain.py
  cit-api/pipeline/models/census.py
  cit-api/pipeline/models/census_economic_region.py
  cit-api/pipeline/models/community.py
  cit-api/pipeline/models/general.py
  cit-api/pipeline/models/health_authority_boundary.py
  cit-api/pipeline/models/indian_reserve_band_name.py
  cit-api/pipeline/models/lake.py
  cit-api/pipeline/models/location_assets.py
  cit-api/pipeline/models/natural_resource_region.py
  cit-api/pipeline/models/opportunity.py
  cit-api/pipeline/models/permitted_major_mines.py
  cit-api/pipeline/models/provincial_electoral_district.py
  cit-api/pipeline/models/railway.py
  cit-api/pipeline/models/river.py
  cit-api/pipeline/models/roads_and_highways.py
Labels: bug, enhancement

#556 CIT 249 opportunities no address
  cit-api/pipeline/migrations/0138_auto_20210329_1530.py
  cit-api/pipeline/models/opportunity.py
  cit3.0-web/src/components/AddMarker/AddMarker.js
  cit3.0-web/src/components/Map/Map.js
  cit3.0-web/src/components/MapContainer/MapContainer.js
  cit3.0-web/src/components/Page/AddOpportunity/AddOpportunity.js
  cit3.0-web/src/helpers/helpers.js
  cit3.0-web/src/helpers/parcelData.js
  cit3.0-web/src/helpers/soil.js
Labels: bug, enhancement
